# Generated by Django 5.1.1 on 2024-10-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_images',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='Images_Profile'),
        ),
    ]
