# Generated by Django 5.1.3 on 2025-02-10 23:58

import utils.generate_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=utils.generate_code.generate_code, max_length=10),
        ),
    ]
