# Generated by Django 5.0.6 on 2024-07-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_rename_first_name_profile_frist_name_user_frist_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='frist_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
    ]
