# Generated by Django 4.2.19 on 2025-02-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_alter_phone_type_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='image',
            field=models.ImageField(blank=True, default='credit.webp', null=True, upload_to='Images_credit', verbose_name='Image'),
        ),
    ]
