# Generated by Django 4.2.19 on 2025-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_alter_address_address_alter_address_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=16, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='country',
            field=models.CharField(max_length=225, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(max_length=3, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date',
            field=models.DateField(verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(max_length=225, verbose_name='Name'),
        ),
    ]
