# Generated by Django 4.2.19 on 2025-02-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0014_alter_creditcard_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Business', 'Business'), ('Office', 'Office'), ('Academy', 'Academy'), ('Other', 'Other')], max_length=20, verbose_name='Type'),
        ),
    ]
