# Generated by Django 5.1.1 on 2024-10-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_company_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='youtube_facebook_link',
            new_name='youtube_link',
        ),
    ]
