# Generated by Django 5.1.1 on 2024-10-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_youtube_facebook_link_company_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='youtube_link',
        ),
    ]
