# Generated by Django 5.1.3 on 2025-01-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
