# Generated by Django 5.1.3 on 2025-01-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cart_coupon_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_after_coupon',
            field=models.FloatField(blank=True, null=True, verbose_name='Total After Coupon'),
        ),
    ]
