# Generated by Django 5.1.3 on 2025-02-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_coupon_users_used_delete_usedcoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users_used',
        ),
    ]
