# Generated by Django 4.2.19 on 2025-02-14 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_deliveryphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='address',
            field=models.TextField(max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='deliveryphone',
            name='type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Third', 'Third')], max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='credit.webp', null=True, upload_to='Images_credit', verbose_name='Image')),
                ('name', models.CharField(max_length=225, verbose_name='Name')),
                ('card_number', models.CharField(max_length=16, verbose_name='Card Number')),
                ('country', models.CharField(max_length=225, verbose_name='Country')),
                ('cvv', models.CharField(max_length=3, verbose_name='CVV')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
