# Generated by Django 4.2.19 on 2025-02-14 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_alter_deliveryaddress_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express', models.CharField(blank=True, max_length=200, null=True, verbose_name='Express')),
                ('start_work', models.DateTimeField(blank=True, null=True, verbose_name='Start Work')),
                ('end_work', models.DateTimeField(blank=True, null=True, verbose_name='End Work')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='orders.deliveryaddress')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_phoens', to='orders.deliveryphone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
