# Generated by Django 4.2.19 on 2025-02-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='phone',
        ),
    ]
