# Generated by Django 4.2.19 on 2025-02-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_delivery_address_remove_delivery_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Bussinees', 'Bussinees'), ('Office', 'Office'), ('Academy', 'Academy'), ('Other', 'Other')], max_length=20, verbose_name='Type'),
        ),
    ]
