# Generated by Django 4.2.19 on 2025-02-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_deliveryaddress_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deliveryphone',
            name='user',
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryPhone',
        ),
    ]
