# Generated by Django 4.2.19 on 2025-02-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_delivery_user_remove_deliveryphone_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='address',
            new_name='delivery_address',
        ),
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='type',
            new_name='type_address',
        ),
    ]
