# Generated by Django 4.2.19 on 2025-02-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_address_deliveryaddress_delivery_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='notes',
            new_name='note',
        ),
    ]
