# Generated by Django 4.2.19 on 2025-02-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_rename_notes_deliveryaddress_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='type_address',
            field=models.CharField(max_length=20, verbose_name='Type'),
        ),
    ]
